# Generated by Django 5.1.3 on 2024-11-19 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevo_gallery', '0001_initial'),
        ('sevo_media', '0003_alter_picture_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sevo_media.picture')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='gallery_pictures',
            field=models.ManyToManyField(blank=True, to='sevo_gallery.gallerypicture'),
        ),
    ]
