# Generated by Django 5.1.3 on 2024-11-19 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevo_gallery', '0002_gallerypicture_gallery_gallery_pictures'),
        ('sevo_media', '0003_alter_picture_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypicture',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sevo_gallery.gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_pictures',
            field=models.ManyToManyField(blank=True, related_name='galeriebilder', to='sevo_gallery.gallerypicture'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='bilder', to='sevo_media.picture'),
        ),
    ]
