# Generated by Django 5.1.3 on 2024-11-20 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevo_gallery', '0003_gallerypicture_gallery_and_more'),
        ('sevo_media', '0004_filetag_alter_picturetag_options_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerypicture',
            options={'verbose_name': 'Gallery Picture', 'verbose_name_plural': 'Gallery Pictures'},
        ),
        migrations.AlterField(
            model_name='gallerypicture',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sevo_gallery.gallery'),
        ),
        migrations.AlterField(
            model_name='gallerypicture',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sevo_media.picture'),
        ),
    ]
