# Generated by Django 5.1.3 on 2024-11-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevo_media', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageTag',
            new_name='PictureTag',
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Picture', 'verbose_name_plural': 'Pictures'},
        ),
        migrations.AlterModelOptions(
            name='picturetag',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Image Tag', 'verbose_name_plural': 'Image Tags'},
        ),
    ]
