# Generated by Django 5.1.3 on 2024-11-17 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevo_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagearticle',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sevo_pages.article'),
        ),
    ]
