# Generated by Django 5.1.3 on 2024-11-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevo_pages', '0004_alter_menu_options_pagemenu_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagemenu',
            options={'ordering': ['order'], 'verbose_name': 'Page Menu', 'verbose_name_plural': 'Page Menus'},
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
