# Generated by Django 5.1.3 on 2024-11-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevo_pages', '0006_remove_page_menu_remove_page_menu_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
