# Generated by Django 5.1.3 on 2024-11-19 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevo_media', '0003_alter_picture_tags'),
        ('sevo_pages', '0007_page_is_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sevo_media.picture'),
        ),
    ]
