# Generated by Django 5.1.3 on 2024-11-11 01:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevo_auth', '0002_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
