# Generated by Django 5.1.3 on 2024-11-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevo_auth', '0003_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
