# Generated by Django 5.1.3 on 2024-11-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immo_test_many2many', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='tags',
            field=models.ManyToManyField(blank=True, to='immo_test_many2many.tag'),
        ),
    ]
